version: '3'

services:
  progress_db:
    env_file: .env
    container_name: progress_db
    image: mysql:5.7
    ports:
      - "${PRO_DB_PORT}:3306"
    networks:
      - progress_backend

  # progress:
    # env_file: .env
    # container_name: progress
    # build: ./Progress
    # command: sh start-sail.sh
    # ports:
      # - "${PRO_PORT}:${PRO_PORT}"
    # networks:
      # - progress_backend

  quiz_db:
    env_file: .env
    container_name: quiz_db
    image: mysql:5.7
    ports:
      - "${QUIZ_DB_PORT}:3306"
    networks:
      - quiz_backend

  quiz_service:
    env_file: .env
    container_name: QuizService
    build: ./QuizService
    command: sh start-sail.sh
    ports:
      - "${QUIZ_PORT}:${QUIZ_PORT}"
    networks:
      - quiz_backend

  playlist_db:
    env_file: .env
    container_name: playlist_db
    image: mysql:5.7
    ports:
      - "${PLAYLIST_DB_PORT}:3306"
    networks:
      - playlist_backend

  playlist_service:
    env_file: .env
    container_name: PlaylistService
    build: ./PlaylistService
    command: sh start-sail.sh
    ports:
      - "${PLAYLIST_PORT}:${PLAYLIST_PORT}"
    networks:
      - playlist_backend

  login_db:
    env_file: .env
    container_name: login_db
    image: mysql:5.7
    ports:
      - "${LOGIN_DB_PORT}:3306"
    networks:
      - login_backend

  login_service:
    env_file: .env
    container_name: LoginService
    build: ./LoginService
    command: sh start-sail.sh
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
    networks:
      - login_backend

networks:
  progress_backend: {}
  quiz_backend: {}
  playlist_backend: {}
  login_backend: {}
