version: '3'

services:
  api-gateway:
    env_file: .env
    container_name: api-gateway
    build: ./ApiGateway
    command: sh start-gateway.sh
    ports:
      - "${API_GATEWAY_PORT}:8080"
    networks:
      - api-gateway

  playlist_db:
    env_file: .env
    container_name: playlist_db
    image: mysql:5.7
    ports:
      - "${PLAYLIST_DB_PORT}:3306"
    networks:
      - playlist_backend

  playlist_service:
    env_file: .env
    container_name: PlaylistService
    build: ./PlaylistService
    command: sh start-sail.sh
    ports:
      - "${PLAYLIST_PORT}:${PLAYLIST_PORT}"
    networks:
      - playlist_backend

  class_management_db:
    env_file: .env
    container_name: class_management_db
    image: mysql:5.7
    ports:
      - "${CLASS_DB_PORT}:3306"
    networks:
      - class_backend

  class_management_service:
    env_file: .env
    container_name: ClassManagementService
    build: ./ClassManagementService
    command: sh start-sail.sh
    ports:
      - "${CLASS_PORT}:${CLASS_PORT}"
    networks:
      - class_backend

  communication_db:
    env_file: .env
    container_name: communication_db
    image: mysql:5.7
    ports:
      - "${COM_DB_PORT}:3306"
    networks:
      - communication_backend

  communication_service:
    env_file: .env
    container_name: communication_service
    build: ./CommunicationService
    command: sh start-sail.sh
    ports:
      - "${COM_PORT}:${COM_PORT}"
    networks:
      - communication_backend

networks:
  api-gateway: {}
  playlist_backend: {}
  class_backend: {}
  communication_backend: {}
